### PR TITLE
make code simple again

### PR DESCRIPTION
**Pull request by cordoval**
@phansys if you can help me with spotting places, this PR will do a lot of cleanings of unnecessary checks in the code

### CODE REVIEW

**Comment by cordoval** [comment]
some commands are not working i think because the symlink .gush.dist is not mounting the project directory in which gush is running. Trying to think of ideas on how to accomplish this.

**Comment by cordoval** [comment]
@phansys https://circleci.com/docs/fork-pr-builds/, the builds on forks are run automatically so no need for you to setup anything. It is only for private repos that you have to explicitly enable it and gush is a public repo so there is no need.

**Comment by phansys** [comment]
@cordoval, my requirement was to enable SSH for that build, so I had to enable explicitly the Circle CI hook in my fork in order to achieve that goal.
Regarding the expected result of this PR, can you please share some specific thoughts about which is the desired result you are looking for?

**Comment by cordoval** [comment]
enable ssh? hmm not sure i still understand.

Re: This PR. I know we have build-in many conditions and checks like the ones i have removed. There are many more things that can be simplified now that we can stick to a fixed environment that is containerized. So no checks for versions of git, version of php 7 so we can use ::class and some other simplifications the latest version of the language brings.

**Comment by phansys** [comment]
image
:+1: for the issue's goal.

**Comment by cordoval** [comment]
early merging

**Pull request merged**
