### PR TITLE
[WIP] remove jira support

### PR DESCRIPTION
**Pull request by cordoval**

### CODE REVIEW

**Comment by glensc** [comment]
WTF?!

**Comment by lauripiisang** [comment]
Not discussed, not documented and not explained. WTF indeed??

**Comment by cordoval** [comment]
Jira support was never working correctly and it had a bug for many months. We can think of adding it back any moment provided those things get solved, but since some of the adapters were totally falling off support I decided to remove them.

**Comment by glensc** [comment]
`branch:changelog` works for me!

**Comment by cordoval** [comment]
@glensc Is branch:changelog the only command you use? what other commands were you using from Jira adapter?

**Comment by glensc** [comment]
i'm not using full power of gush, for now, branch:changelog was first touch using jira adapter, i do not know what's out there. there's no documentation (anymore?).

and i (nor you) shouldn't be the base of decision what features to keep... that's my opinion

**Pull request merged**
