### PR TITLE
fix missing exit-code when exception is thrown

### PR DESCRIPTION
**Pull request by sstok**
|Q            |A  |
|---          |---|
|Fixed Tickets|   |
|License      |MIT|

### CODE REVIEW

**Comment by sstok** [comment]
whoops this should be merged into 1.0 :)

**Comment by pierredup** [comment]
Shouldn't L296 be `return $exitCode;` instead of `return return $event->getExitCode();`?

**Comment by sstok** [comment]
Indeed, good catch.

**Comment by sstok** [comment]
fixed by ad25db0e70a1ec6a6f164ef6b2dbd4b9305220eb

**Comment by sstok** [comment]
Still not fully correct :see_no_evil: 

ConsoleTerminateEvent can set the Exit code which is not used anymore now.
The TERMINATE event should actually be dispatched before the EXCEPTION event is dispatched (thats how its done in the parent class).

So the finally was actually mistake :neutral_face:

**Comment by sstok** [comment]
See #431

**Pull request closed without merging**
