### PR TITLE
Upgraded symfony

### PR DESCRIPTION
**Pull request by GrahamCampbell**
This looks ok to me, superficially, but I've not made details checking. Perhaps care needs to be taken with upgrading the console component in particular.

### CODE REVIEW

**Comment by cordoval** [comment]
I like upgrading packages except symfony since there is not a strong reason for doing it, but oh well. Tests pass and we shall see if all was worth it in the coming weeks if things fail :+1:

**Comment by GrahamCampbell** [comment]
This will be the last symfony upgrade gush can make if it wants to remain php 5.4 compatible.

**Comment by cordoval** [comment]
we will soon be departing from 5.4 imo :+1: again

**Comment by GrahamCampbell** [comment]
Maybe a good time to do it would be when php 5.5 get's EOLed in June 2016?

**Comment by GrahamCampbell** [comment]
So 5.4 is way past being EOL, so far so the next version is EOL too, lol.

**Pull request merged**
