### PR TITLE
Use SSH agent forwarding instead of SSH keys

### PR DESCRIPTION
**Pull request by phansys**
|Q            |A   |
|---          |--- |
|Fixed tickets|#595|
|License      |MIT |
                    

[Using SSH agent forwarding](https://developer.github.com/guides/using-ssh-agent-forwarding/).

### CODE REVIEW

**Comment by sstok** [comment]
You need to also configure the host system, but which hostname is used?

**Comment by sstok** [comment]
It seems it's not possible to forward the SSH agent socket into a container, I found multiple issues and complaints indicating this is not possible.

@phansys please confirm this is possible, but I simple need to change something on my system (macOS) 🙏

**Comment by phansys** [comment]
Sure @sstok, this works. I've created this PR with the Docker image using these settings. I had to do this change because with the keys approach, the container was prompting for the passphrase every time:
```
$ gush pull-request:create -vvv
CMD git rev-parse --show-toplevel
CMD git rev-parse --abbrev-ref HEAD
CMD git config --local --get remote.gushphp.url
CMD git config --local --get remote.gushphp.url
CMD git remote update gushphp
Enter passphrase for key '/root/.ssh/id_rsa': 
CMD git rev-list gushphp/master..ssh_auth_sock --count

Open request on gushphp/gushphp
================================

 phansys wants to merge 3 commits into gushphp/gushphp:master from phansys:ssh_auth_sock.

CMD git ls-remote git@github.com:phansys/gushphp.git
Enter passphrase for key '/root/.ssh/id_rsa': 
```

**Comment by sstok** [comment]
Indeed, but I wonder why it's not working on my system 😫

**Comment by phansys** [comment]
You have SSH agent running locally?
Check these points:
* [Your local ssh-agent must be running](https://developer.github.com/guides/using-ssh-agent-forwarding/#your-local-ssh-agent-must-be-running)
* [Your key must be available to ssh-agent](https://developer.github.com/guides/using-ssh-agent-forwarding/#your-key-must-be-available-to-ssh-agent)

**Comment by phansys** [comment]
Please, let me know if you have any news on this. I'll try to help where possible.

**Comment by phansys** [comment]
The container can't be different (or at least is what I think). IMO, there is no need to `ssh-agent` to be running on the container, I think you should check with `ssh -T git@github.com` instead: [Testing SSH agent forwarding](https://developer.github.com/guides/using-ssh-agent-forwarding/#testing-ssh-agent-forwarding).

**Comment by sstok** [comment]
ssh-agent is not running on the Container, but on the host system ;)

On the host I get an successful authentication and a result when running `ssh-add -L`
But in the bash of the container I get `Error connecting to agent: Connection refused`

```
bash-4.3# ssh -T git@github.com
Permission denied (publickey).
```

**Comment by cordoval** [comment]
hmm i am going to try now

**Comment by phansys** [comment]
Let me change my entrypoint in order to compare my output with yours.

**Comment by phansys** [comment]
```
bash-4.3# stat stat $SSH_AUTH_SOCK
stat: can't stat 'stat': No such file or directory
  File: /ssh-agent
  Size: 0         	Blocks: 0          IO Block: 4096   socket
Device: 2dh/45d	Inode: 11          Links: 1
Access: (0775/srwxrwxr-x)  Uid: ( 1000/ UNKNOWN)   Gid: ( 1000/ UNKNOWN)
Access: 2016-08-03 18:07:14.000000000
Modify: 2016-07-31 14:15:39.000000000
Change: 2016-07-31 14:15:39.000000000

bash-4.3# ssh -T git@github.com
Hi phansys! You've successfully authenticated, but GitHub does not provide shell access.
```

**Comment by phansys** [comment]
Note the difference at `Access` section:
Yours:
Access: (0666/srw-rw-rw-)  Uid: (    0/    root)   Gid: (    0/    root)
Mine:
`Access: (0775/srwxrwxr-x)  Uid: ( 1000/ UNKNOWN)   Gid: ( 1000/ UNKNOWN`

**Comment by cordoval** [comment]
test it outside of gush project, i am getting errors like this:

```
  [RuntimeException]
  Permission denied (publickey).
  fatal: Could not read from remote repository.
  Please make sure you have the correct access rights
  and the repository exists.
```

**Comment by phansys** [comment]
Let me do some changes in order to match the @sstok's output, changing file permissions, executing `docker run` specifying another user with `--user` option.

**Comment by phansys** [comment]
I've updated the file permissions manually and my access is kept intact:
```
bash-4.3# stat $SSH_AUTH_SOCK
  File: /ssh-agent
  Size: 0         	Blocks: 0          IO Block: 4096   socket
Device: 2dh/45d	Inode: 11          Links: 1
Access: (0666/srw-rw-rw-)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-08-04 15:04:15.000000000
Modify: 2016-07-31 14:15:39.000000000
Change: 2016-08-04 15:04:13.000000000

bash-4.3# ssh -T git@github.com
Hi phansys! You've successfully authenticated, but GitHub does not provide shell access.
```

**Comment by sstok** [comment]
```
docker run -it \
    -v $SSH_AUTH_SOCK:/ssh-agent \
    -v ~/.ssh/known_hosts:/root/.ssh/known_hosts \
    -v ~/.gush:/root/.gush \
    -v "$(pwd)":/root/project \
    -v /etc/passwd:/etc/passwd:ro \
    -e SSH_AUTH_SOCK=/ssh-agent \
    -e GUSH_CONFIG=/root/.gush \
    -e GUSH_LOCAL_CONFIG=/root/project \
    -u $UID \
    gush "$@"
```

```
bash-4.3$ id
uid=501 gid=0(root)
bash-4.3$ ssh -T git@github.com
No user exists for uid 501
```

**Comment by phansys** [comment]
```
bash-4.3# id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
```

**Comment by phansys** [comment]
Passing `-u $UID` to `docker run` I can reproduce your issue:
```
bash-4.3$ id
uid=1000 gid=0(root)
bash-4.3$ stat $SSH_AUTH_SOCK
  File: /ssh-agent
  Size: 0         	Blocks: 0          IO Block: 4096   socket
Device: 2dh/45d	Inode: 11          Links: 1
Access: (0666/srw-rw-rw-)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-08-04 15:04:15.000000000
Modify: 2016-07-31 14:15:39.000000000
Change: 2016-08-04 15:04:13.000000000

bash-4.3$ ssh -T git@github.com
No user exists for uid 1000
bash-4.3$ id
uid=1000 gid=0(root)
```

**Comment by phansys** [comment]
Could you then pass the hardcoded UID `-u 0` or it could be better to try fixing permissions inside the container? Please, tell me about your results.

**Comment by sstok** [comment]
using the `-u 0` did not solve the problem. I have absolutely no idea why it's not working 💀

**Comment by phansys** [comment]
So, just for recap, now your UID is `0` at the container and you still have no access?
Which is the output for `ssh -T git@github.com` now? Could you try running verbose? `ssh -T git@github.com -vvv`

**Comment by sstok** [comment]
See attachments.

[git-t-with-default.txt](https://github.com/gushphp/gush/files/402181/git-t-with-default.txt)
[git-t-with-uid-0.txt](https://github.com/gushphp/gush/files/402182/git-t-with-uid-0.txt)

**Comment by phansys** [comment]
The difference between your output and mine is from line 89, and note that your debug level stop at 1 there while mine forwards to 2:
**Yours**
```
debug1: SSH2_MSG_NEWKEYS received
debug1: pubkey_prepare: ssh_get_authentication_socket: Connection refused
```
**Mine**
```
debug1: SSH2_MSG_NEWKEYS received
debug2: key: phansys@gmail.com (0x558ddb96e440), agent
```

**Comment by phansys** [comment]
Could you please check the bitmask for your private and public key @sstok? https://help.ubuntu.com/community/SSH/OpenSSH/Keys

**Comment by cordoval** [comment]
hmm the problem of permission is common on the internets i bet, i just saw days ago an entry but didn't follow it through. I hope we can solve this.

**Comment by sstok** [comment]
SSH agent is running, I can connect with the native system (macOS), but as soon as I enter Docker it refuses to connect! 😠 

It almost seems Docker refuses to mount the socket file or something.

On macOS:
```bash
$ echo "he" > $SSH_AUTH_SOCK
zsh: operation not supported on socket: /private/tmp/com.apple.launchd.zYkDnlWlB6/Listeners
```

In Docker:
```bash
bash-4.3# echo "he" > $SSH_AUTH_SOCK
bash: /ssh-agent: No such device or address
```

Btw I'm using the latest version of Docker: Docker version 1.12.0, build 8eab29e

**Comment by sstok** [comment]
I did some testing with a PHP script, creating a local socket and in on the host it work, BUT!! As soon as Docker tries to communicate with the mounted socket everything fails (again).

```
Attempting to connect to '/tmp/php-my-socket.sock'
Warning: socket_connect(): unable to connect [111]: Connection refused in /root/project/socket-client.php on line 22
socket_connect() failed.
Reason: () Connection refused
```

**Comment by sstok** [comment]
OK, reinstalling the Docker toolbox did not solve the mounting problem 💀

**Comment by phansys** [comment]
Don't give up @sstok, just for clarification, I'm using Linux, while you and @cordoval are on Mac; I don't know if there is some different configuration, but I'll try to do a further investigation later.

**Pull request merged**
