### PR TITLE
move adapters to home repo

### PR DESCRIPTION
**Pull request by cordoval**
addressing #489

### CODE REVIEW

**Comment by cordoval** [comment]
@GrahamCampbell StyleCI has a bug. The headers were duplicated because they are different.
Please let me know, if not i can run the gush command to format the headers since i remember it does it correctly. Also i had to download by hand the patch and apply it, i remember we have a fabpot command to do the apply patch automatically. Maybe you want to send a command to do that with SyleCI, i did not see easily how to send a PR.

**Comment by cordoval** [comment]
@sstok not sure why scrutinizer crashes. Any hint?

Other than this we can merge this :+1:

**Comment by cordoval** [comment]
also since i believe it is a waste of time to maintain the other repos let's remove them from gush main organization and also deprecate them on packagist. I think that is all that is left. Tests and further refactoring can wait for follow up PRs.

**Comment by pierredup** [comment]
IMO the 'ThirdParty' namespace doesn't really make sense, since the adapters is not part of a 3rd party, but part of Gush core and now just lives in the main repo.

**Comment by sstok** [comment]
I agree with @pierredup on the namespace part.

But we can't delete repositories just yet as some still use Gush with Composer (global).
We should keep them for about a year and then remove them.

**Comment by cordoval** [comment]
we can change to any other name you want without problems. This is more so that we get the repos in.

**Comment by cordoval** [comment]
I think there was a ticket in which we discouraged the global composer for gush. Recommended ways are clone and symlink AND phar.

**Comment by sstok** [comment]
hmm :) what is the common name used in other situations?

We can use the `Adapter` sub namespace and change it once we have better name.
Just make sure they are marked `@internal` so we can easily change them (if anyone would use Gush as a library ;) )

> I think there was a ticket in which we discouraged the global composer for gush. 
Hmm, OK :)

**Comment by cordoval** [comment]
Adapter conflicts with Adapter folder already existing. That is why I choose the non nice Third Party.

**Comment by cordoval** [comment]
we can definitely not put the generic Adapter classes together with the third party adapters implementations.

**Comment by cordoval** [comment]
looks like scrutinizer passed

**Pull request merged**
