### PR TITLE
Refactor and simplify some code

### PR DESCRIPTION
**Pull request by phansys**
|Q            |A   |
|---          |--- |
|Fixed tickets|#600|
|License      |MIT |

### CODE REVIEW

**Comment by cordoval** [comment]
@phansys please rebase as i merged some changes just now, we need to fix spurious things yeah

**Comment by cordoval** [comment]
opening a new Pr with your changes

**Comment by cordoval** [comment]
@phansys would be good if this Pr is only that change for directory.

**Comment by phansys** [comment]
Done.

**Pull request merged**
