### PR TITLE
add PullRequestCheckoutCommand

### PR DESCRIPTION
**Pull request by cordoval**
|Q            |A  |
|---          |---|
|Fixed Tickets|   |
|License      |MIT|

### CODE REVIEW

**Comment by cordoval** [comment]
you have permissions to my fork @sstok i just rebased and reopened your PR here

**Comment by sstok** [comment]
Rebase on master and it should be good.

**Comment by cordoval** [comment]
so this is good to merge? what about the problem?

**Comment by cordoval** [comment]
@sstok did you see this https://github.com/symfony/symfony/issues/15032#issuecomment-121189915 ? is this related?

**Comment by sstok** [comment]
Its fixed in the master ;) lock symfony/console at 2.7.1

**Comment by cordoval** [comment]
pending the merge of this one https://github.com/symfony/symfony/pull/15271

**Comment by sstok** [comment]
:shipit:

**Comment by cordoval** [comment]
great job @sstok

**Pull request merged**
