### PR TITLE
remove crap go docker

### PR DESCRIPTION
**Pull request by cordoval**

### CODE REVIEW

**Comment by cordoval** [comment]
@sstok hmm i wonder if the git commands will be run correctly though

**Comment by sstok** [comment]
Can you explain what you are doing here? I don't think forcing users to install Docker is a good idea, especially on Windows where it's not possible to use local directories.

**Comment by cordoval** [comment]
yeah we will depart probably from windows support, if it is not supported on windows one way or another. I detail what i am trying to do and yet not sure how possible would it be. Dockerize gush. That way we move to circleci, we run tests through it and with docker and just take it from there, it will be a great replacement for phar crap.

**Comment by sstok** [comment]
Windows users can still run Gush by cloning/downloading it and then making an alias for the command (that's how I solved it :) ) only need some clear instructions for users.

Before going through with this we should ask how many users are running Gush on Windows.
I know it's possible but there are (were?) some tricks to make it work with SSH and encrypted key file (or else you need to leave it uncrypted 😱 ) and colors require a compatible terminal.

One plus-side (I cannot believe I'm saying this) of Windows is that you install multiple PHP versions at the same time, so you would have a Gush self-contained directory with Gush and a compatible PHP version (something we can look at when there is actual demand for this).

I'm already using PHP 7 :metal: so for me it's no problem.

**Comment by cordoval** [comment]
```
One plus-side (I cannot believe I'm saying this) of Windows is that you install multiple PHP versions at the same time, so you would have a Gush self-contained directory with Gush and a compatible PHP version (something we can look at when there is actual demand for this).
```

maybe i am misunderstanding but i wanted to answer that with docker this is not problem because it is already encapsulated

**Comment by sstok** [comment]
> maybe i am misunderstanding but i wanted to answer that with docker this is not problem because it is already encapsulated

But that doesn't work on Windows as you'd expect 😈 at least that's what I'm thinking, actually would have to test that 😄

**Comment by cordoval** [comment]
Gush is "working" on docker but 

```php
(new Gush\Application($adapterFactory, ConfigFactory::createConfig(getcwd())))->run();
```

that getcwd and the fact that we need to pass a .gush.yml file means that we have to mount a volume where we can exchange files. Presumably the whole project folder is to be mounted to which i am not opposed since it makes sense but just have not tried it.

**Comment by cordoval** [comment]
we will go in steps

**Comment by phansys** [comment]
@cordoval, I'm not against to dockerize the tool, but removing the phar left out the simple install via `composer require -g gushphp/gush`.

**Comment by cordoval** [comment]
i am fully aware of that and it was deliberate. That way there is more pressure to finish the docker integration.

**Pull request merged**
