### PR TITLE
Fix adapter factories

### PR DESCRIPTION
**Pull request by sstok**
|Q            |A   |
|---          |--- |
|Fixed Tickets|#500 |
|License      |MIT |

### CODE REVIEW

**Comment by sstok** [comment]
(PR squashed)

**Comment by sstok** [comment]
Tested every but the GitHub adapter :children_crossing:

**Comment by sstok** [comment]
@AlexKovalevych can you please confirm this fixes #421

**Comment by AlexKovalevych** [comment]
@sstok Nope, it doesnt, as i said i'm not sure its connected with gush, but probably with underlying gitlab library.

**Comment by sstok** [comment]
Ok, `issue:create` was working for GitLab.com so we need look into this further.

**Pull request merged**
