### PR TITLE
Reintroduce compatibility for PHP 5.4

### PR DESCRIPTION
**Pull request by sstok**
|Q            |A  |
|---          |---|
|Fixed Tickets|   |
|License      |MIT|

This actually turned out to be very simple :)

### CODE REVIEW

**Comment by pierredup** [comment]
:+1:

**Comment by aik099** [comment]
::+1::

**Comment by GrahamCampbell** [comment]
Lots of unused imports now.

**Comment by GrahamCampbell** [comment]
See StyleCI's diff.

**Comment by GrahamCampbell** [comment]
> Reintroduce compatibility for PHP 5.4

:-1: It's already EOL.

**Comment by cordoval** [comment]
This was never a good idea :-1:

**Comment by aik099** [comment]
Decision to upgrade the PHP version on it's developer machine is up to each developer individually. Forcing Gush users to install newer PHP version just because is like forcing people to install Windows 8 even though app works on Windows 7 without problems.

**Comment by GrahamCampbell** [comment]
> Forcing Gush users to install newer PHP version just because is like forcing people to install Windows 8 even though app works on Windows 7 without problems.

I'm fine with that. :trollface:

**Comment by pierredup** [comment]
I haven't used PHP 5.4 in a while (I stopped using it the day 5.5 was released). But not all developers upgrade their development environment frequently (I actually know developers still using PHP 5.3).

But 5.5 doesn't provide any useful functionality that we can use at the moment. This is a small change in order to please a wider range of developers that want to use Gush. Maintaining 5.4 compatibility isn't a hard thing to do, and when we want to start using more of the features in 5.5 (generators etc) then the minimum requirement can be bumped. But until that happens it doesn't make sense to require >= 5.5 just for the class constant and limit the project to a smaller number of users

**Comment by cordoval** [comment]
i am convinced now it is a simple change. I am reviewing it and will merge after that.

**Comment by cordoval** [comment]
done. That done and said.

I have to leave something very clear. Gush is a beloved project and being so it express the emotions and passion of the thriving spirit for good development of its creators and maintainers. So in the future case where there is a conflict where we have at stake the upgrading to gain enhancements or simplicity or readability etc, there can be a change of mind. I always wanted to navigate on bleeding edge because it helps you see new stuff and do things better. That said also, we are now happier letting other devs join and hopefully upgrade on their time.

I also supported old projects, but you can use tools to switch php versions nowadays. I even switch by hand if need be. But gush is ok to let it run on the latest for my case. In any case, we are now happy.

**Comment by cordoval** [comment]
thanks @pierredup for shedding sober light and convince me. :+1:

**Pull request merged**
