### PR TITLE
Removed pointless badges

### PR DESCRIPTION
**Pull request by GrahamCampbell**
The dependences badge is wrong and seems pointless to me. The total downloads badge doesn't seem that useful either since it doesn't reflect the actual usage.

### CODE REVIEW

**Comment by sstok** [comment]
:+1:

**Comment by sstok** [comment]
@GrahamCampbell did you remove your fork?

**Comment by cordoval** [comment]
what is this unknown repository you are sending your PR from @GrahamCampbell ?

**Comment by cordoval** [comment]
if you remove your repository then we cannot merge with gush, so thanks we found a bug i guess :+1:

**Pull request merged**
