### PR TITLE
Create a new command to show Pull Request details

### PR DESCRIPTION
**Pull request by shulard**
We have for the moment a `issue:show`, I think having a `pull-request:show` is nice too. It's the same logic than for issue :
- It display general details / description
- A flag `--with-comments` allow to display comments
- [x] Add tests

### CODE REVIEW

**Comment by cordoval** [comment]
add description txt with a checkbox for add test

**Comment by shulard** [comment]
Hello,

I've just added a test to validate command execution. This command will be able to dump PullRequest details like :

```
Pull Request #10 - Write a behat test to launch strategy by weaverryan [open]
=============================================================================

 Org/Repo:         gushphp/gush
 Link:             https://github.com/gushphp/gush/pull/10
 Labels:           actionable, easy pick
 Milestone:        some_good_stuff
 Assignee:         cordoval
 Source => Target: cordoval/gush#head_ref => gushphp/gush#base_ref

Body
----

 Help me conquer the world. Teach them to use Gush.
```

This PR is ready for a review.

**Comment by cordoval** [comment]
bump @shulard please rebase so i can review

thanks

**Comment by shulard** [comment]
I've juste rebased on master.

**Pull request merged**
